openapi: 3.0.0
info:
  title: stock-prediction-api
  version: '1.0'
  description: "Dshack Stock Prediction Dashboard's RESTful API"
  contact:
    name: ds-hack
    email: datascientist.toolbox.com@gmail.com
    url: 'https://datascientist-toolbox.com/'
  termsOfService: 'https://datascientist-toolbox.com/'
servers:
  - url: 'http://localhost:8080'
    description: dshack-development
  - url: 'http://localhost:10080'
    description: dshack-staging
  - url: 'http://localhost:20080'
    description: dshack-production
paths:
  /companies:
    get:
      summary: GetCompanies
      tags:
        - Company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      operationId: getCompanies
      description: ユーザーが、Dashboardにて登録している企業の基本公開情報を取得します。
      security:
        - basicAuth: []
    post:
      summary: PostCompanies
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ../common/models/success.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      operationId: postCompanies
      description: ユーザーが、株価モニタリング・予測対象として登録画面から新規に企業を登録します。
      security:
        - basicAuth: []
      parameters:
        - schema:
            type: string
            maxLength: 4
            minLength: 4
          in: query
          name: companyId
          description: 新規登録対象として指定する企業ID
          required: true
          explode: false
    delete:
      summary: DeleteCompanies
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../common/models/success.v1.yaml
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: ../common/models/error.v1.yaml
      operationId: deleteCompanies
      security:
        - basicAuth: []
      description: ユーザーが、株価モニタリング・予測対象として登録済の企業の登録を削除します。
      parameters:
        - schema:
            type: string
            maxLength: 4
            minLength: 4
          in: query
          name: companyId
          description: 登録解除対象として指定する企業ID
          required: true
          explode: false
    parameters: []
  /companies/search:
    get:
      summary: SearchCompanies
      tags:
        - Company
      responses:
        '200':
          description: OK
      operationId: searchCompanies
      description: 株価のモニタリング・予測対象として登録可能な企業を検索条件により絞り込み取得します。
      parameters:
        - schema:
            type: string
          in: query
          name: companyName
          description: 部分一致の検索条件となる企業名。カンマ区切りで複数指定可能。
          explode: false
        - schema:
            type: string
          in: query
          name: stockCode
          description: 銘柄コード。カンマ区切りで複数指定可能。
          explode: false
  /stockprices/timeseries:
    get:
      summary: GetStockPricesTimeSeries
      tags:
        - StockPrice
      responses:
        '200':
          description: OK
      operationId: getStockPricesTimeSeries
      description: ユーザーが、株価モニタリング・予測対象として登録している企業の株価の時系列データを取得します。クエリパラメータにて、詳細な取得条件を絞ることが出来ます。
      security:
        - basicAuth: []
      parameters:
        - schema:
            type: string
          in: query
          name: companyId
          description: ユーザーが、株価モニタリング・予測対象として登録している企業ID。複数存在する場合はカンマで区切る。
          required: true
          explode: false
        - schema:
            type: boolean
            default: 'false'
          in: query
          name: isPrediction
          description: 予測期間を表示する場合はtrue、表示しない場合はfalseを指定
        - schema:
            type: string
          in: query
          name: startDate
          description: 株価データ取得の開始日
        - schema:
            type: string
          in: query
          name: endDate
          description: 株価データ取得の終了日。予測期間は含まない。
        - schema:
            type: integer
            minimum: 1
            default: 1
          in: query
          name: period
          description: 時系列データの取得周期を日数で指定する
tags:
  - name: Company
    description: 株価モニタリング・予測対象の企業に関連するAPI
  - name: StockPrice
    description: 株価の時系列データや予測に関連する情報を取得するAPI
security:
  - basicAuth: []
components:
  schemas: {}
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
