basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: datascientist.toolbox.com@gmail.com
    name: Contact us
    url: https://datascientist-toolbox.com/
  description: Demonstration api for dshack project
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Stock Prediction API
  version: "1.0"
paths: {}
swagger: "2.0"
