apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dshack-development
  name: dshack-api-configmap
  labels:
    env: dev
data:
  POSTGRES_HOST: postgres-sts-0.postgres-svc.dshack-development.svc.cluster.local
  POSTGRES_PORT: "5432"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dshack-development
  name: dshack-api-app
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: dshack-api-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dshack-api-app
    spec:
      containers:
      - name: dshack-api-app
        image: dshacks/dshack-api-app-development
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        envFrom:
          - configMapRef:
              name: dshack-api-configmap
---
apiVersion: v1
kind: Service
metadata:
  namespace: dshack-development
  name: dshack-api-svc
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: dshack-api-app
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 8080
    targetPort: 8080